language: node_js
node_js:
  - "7"
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y curl build-essential
script:
  - cd client
  - npm install
  - npm run-script lint
  - npm test
